release_minor: v6.2.0
{"version":"v6.2.0","inputs":"server=6.2.0","type":"minor"}

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -97,15 +97,15 @@ internal:
           cmd: |
             branch="internal/release-{{version}}"
             git push origin "$branch"
-        - name: "github:pr"
-          cmd: |
-            set -eu
-            gh pr create \
-              --fill \
-              --draft \
-              --title "(internal) release_major: build {{version}}" \
-              --body "Test plan: automated release PR, CI will perform additional checks"
-            echo "🚢 Please check the associated CI build to ensure the process completed".
+        # - name: "github:pr"
+        #   cmd: |
+        #     set -eu
+        #     gh pr create \
+        #       --fill \
+        #       --draft \
+        #       --title "(internal) release_major: build {{version}}" \
+        #       --body "Test plan: automated release PR, CI will perform additional checks"
+        #     echo "🚢 Please check the associated CI build to ensure the process completed".
   finalize:
     steps:
       - name: "notifications"
@@ -204,99 +204,99 @@ test:
           exit 1
         fi
 
-promoteToPublic:
-  create:
-    steps:
-      - name: "git"
-        cmd: |
-          set -eu
-          branch="internal/release-{{version}}"
-          echo "Checking out origin/${branch}"
-          git fetch origin "${branch}"
-          git switch "${branch}"
-      # Since we're promoting to public we need to remove the "internal" from the family
-      - name: "family(name):docker-mirror"
-        cmd: comby '["sourcegraph-executors-docker-mirror-:[family_tag_hole~\d+-\d+]-*"]' "[\"sourcegraph-executors-docker-mirror-:[family_tag_hole]-*\"]" -i -f .tf
-      - name: "family(name):sourcegraph"
-        cmd: comby '["sourcegraph-executors-:[family_tag_hole~\d+-\d+]-*"]' "[\"sourcegraph-executors-:[family_tag_hole]-*\"]" -i -f .tf
-      - name: "git:branch"
-        cmd: |
-          set -eu
-          branch="promote/release-{{version}}"
-          git switch -c "${branch}"
-      - name: "git:commit"
-        cmd: |
-          set -eu
-          branch="promote/release-{{version}}"
-          find . -name "*.yaml" | xargs git add
-          find . -name "*.yml" | xargs git add
+# promoteToPublic:
+#   create:
+#     steps:
+#       - name: "git"
+#         cmd: |
+#           set -eu
+#           branch="internal/release-{{version}}"
+#           echo "Checking out origin/${branch}"
+#           git fetch origin "${branch}"
+#           git switch "${branch}"
+#       # Since we're promoting to public we need to remove the "internal" from the family
+#       - name: "family(name):docker-mirror"
+#         cmd: comby '["sourcegraph-executors-docker-mirror-:[family_tag_hole~\d+-\d+]-*"]' "[\"sourcegraph-executors-docker-mirror-:[family_tag_hole]-*\"]" -i -f .tf
+#       - name: "family(name):sourcegraph"
+#         cmd: comby '["sourcegraph-executors-:[family_tag_hole~\d+-\d+]-*"]' "[\"sourcegraph-executors-:[family_tag_hole]-*\"]" -i -f .tf
+#       - name: "git:branch"
+#         cmd: |
+#           set -eu
+#           branch="promote/release-{{version}}"
+#           git switch -c "${branch}"
+#       - name: "git:commit"
+#         cmd: |
+#           set -eu
+#           branch="promote/release-{{version}}"
+#           find . -name "*.yaml" | xargs git add
+#           find . -name "*.yml" | xargs git add
 
-          # Careful with the quoting for the config, using double quotes will lead
-          # to the shell dropping out all quotes from the json, leading to failed
-          # parsing.
-          git commit --allow-empty -am 'promote-release: {{version}}' -m '{{config}}'
-          git push origin "${branch}"
-      - name: "github:pr"
-        cmd: |
-          set -eu
-          internal_branch="internal/release-{{version}}"
-          gh pr create \
-            --fill \
-            --draft \
-            --base "$internal_branch" \
-            --title "(promote) release: build {{version}}" \
-            --body "Test plan: automated release PR, CI will perform additional checks"
-          echo "🚢 Please check the associated CI build to ensure the process completed".
-  finalize:
-    steps:
-      # - name: 'Promote on release registry'
-      #   cmd: |
-      #     echo "Promoting terraform-aws-executors {{version}} release on release registry"
-      #     body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '' "https://releaseregistry.sourcegraph.com/v1/releases/terraform-aws-executors/{{version}}/promote")
-      #     exit_code=$?
+#           # Careful with the quoting for the config, using double quotes will lead
+#           # to the shell dropping out all quotes from the json, leading to failed
+#           # parsing.
+#           git commit --allow-empty -am 'promote-release: {{version}}' -m '{{config}}'
+#           git push origin "${branch}"
+#       - name: "github:pr"
+#         cmd: |
+#           set -eu
+#           internal_branch="internal/release-{{version}}"
+#           gh pr create \
+#             --fill \
+#             --draft \
+#             --base "$internal_branch" \
+#             --title "(promote) release: build {{version}}" \
+#             --body "Test plan: automated release PR, CI will perform additional checks"
+#           echo "🚢 Please check the associated CI build to ensure the process completed".
+#   finalize:
+#     steps:
+#       # - name: 'Promote on release registry'
+#       #   cmd: |
+#       #     echo "Promoting terraform-aws-executors {{version}} release on release registry"
+#       #     body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '' "https://releaseregistry.sourcegraph.com/v1/releases/terraform-aws-executors/{{version}}/promote")
+#       #     exit_code=$?
 
-      #     if [ $exit_code != 0 ]; then
-      #       echo "❌ Failed to promote release on release registry, got:"
-      #       echo "--- raw body ---"
-      #       echo $body
-      #       echo "--- raw body ---"
-      #       exit $exit_code
-      #     else
-      #       echo "Release promoted, see:"
-      #       echo $body
-      #     fi
-      - name: git:tag
-        cmd: |
-          set -eu
+#       #     if [ $exit_code != 0 ]; then
+#       #       echo "❌ Failed to promote release on release registry, got:"
+#       #       echo "--- raw body ---"
+#       #       echo $body
+#       #       echo "--- raw body ---"
+#       #       exit $exit_code
+#       #     else
+#       #       echo "Release promoted, see:"
+#       #       echo $body
+#       #     fi
+#       - name: git:tag
+#         cmd: |
+#           set -eu
 
-          # Branches
-          internal_branch="internal/release-{{version}}"
-          promote_branch="promote/release-{{version}}"
-          release_branch="release-{{version}}"
+#           # Branches
+#           internal_branch="internal/release-{{version}}"
+#           promote_branch="promote/release-{{version}}"
+#           release_branch="release-{{version}}"
 
-          # Create the final branch holding the tagged commit
-          git checkout "${promote_branch}"
-          git switch -c "${release_branch}"
-          git tag {{version}}
-          git push origin ${release_branch} --tags
+#           # Create the final branch holding the tagged commit
+#           git checkout "${promote_branch}"
+#           git switch -c "${release_branch}"
+#           git tag {{version}}
+#           git push origin ${release_branch} --tags
 
-          # Web URL to the tag
-          tag_url="https://github.com/sourcegraph/terraform-aws-executors/tree/{{version}}"
+#           # Web URL to the tag
+#           tag_url="https://github.com/sourcegraph/terraform-aws-executors/tree/{{version}}"
 
-          # Annotate PRs
-          cat << EOF | gh pr comment "$internal_branch" --body-file -
-          - :green_circle: Release has been promoted, see tag: $tag_url.
-          - :no_entry: Do not under any circumstance delete the branch holding the tagged commit (i.e. \`$release_branch\`).
-          - :arrow_right: You can safely close the PR and delete its a associated branch.
-          EOF
+#           # Annotate PRs
+#           cat << EOF | gh pr comment "$internal_branch" --body-file -
+#           - :green_circle: Release has been promoted, see tag: $tag_url.
+#           - :no_entry: Do not under any circumstance delete the branch holding the tagged commit (i.e. \`$release_branch\`).
+#           - :arrow_right: You can safely close the PR and delete its a associated branch.
+#           EOF
 
-          cat << EOF | gh pr comment "$promote_branch" --body-file -
-          - :green_circle: Release has been promoted, see tag: $tag_url.
-          - :no_entry: Do not under any circumstance delete the branch holding the tagged commit (i.e. \`$release_branch\`).
-          - :arrow_right: You can safely close that PR and delete its a associated branch.
-          EOF
+#           cat << EOF | gh pr comment "$promote_branch" --body-file -
+#           - :green_circle: Release has been promoted, see tag: $tag_url.
+#           - :no_entry: Do not under any circumstance delete the branch holding the tagged commit (i.e. \`$release_branch\`).
+#           - :arrow_right: You can safely close that PR and delete its a associated branch.
+#           EOF
 
-          # Annotate build
-          cat << EOF | buildkite-agent annotate --style info
-          Promoted release is **publicly available** through a git tag at [\`{{version}}\`](https://github.com/sourcegraph/terraform-aws-executors/tree/{{version}}).
-          EOF
+#           # Annotate build
+#           cat << EOF | buildkite-agent annotate --style info
+#           Promoted release is **publicly available** through a git tag at [\`{{version}}\`](https://github.com/sourcegraph/terraform-aws-executors/tree/{{version}}).
+#           EOF
