update

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -124,26 +124,26 @@ internal:
           Internal release is ready for promotion under the branch [\`$branch\`](https://github.com/sourcegraph/terraform-aws-executors/tree/$branch).
           EOF
 
-      - name: 'Register on release registry'
-        cmd: |
-          echo "Registering internal terraform-aws-executors {{version}} release on release registry"
-          body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '{
-              "name": "terraform-aws-executors",
-              "version": "{{version}}",
-              "git_sha": "'${COMMIT_SHA}'"
-            }' "https://releaseregistry.sourcegraph.com/v1/releases")
-          exit_code=$?
+      # - name: 'Register on release registry'
+      #   cmd: |
+      #     echo "Registering internal terraform-aws-executors {{version}} release on release registry"
+      #     body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '{
+      #         "name": "terraform-aws-executors",
+      #         "version": "{{version}}",
+      #         "git_sha": "'${COMMIT_SHA}'"
+      #       }' "https://releaseregistry.sourcegraph.com/v1/releases")
+      #     exit_code=$?
 
-          if [ $exit_code != 0 ]; then
-            echo "❌ Failed to create release in release registry, got:"
-            echo "--- raw body ---"
-            echo $body
-            echo "--- raw body ---"
-            exit $exit_code
-          else
-            echo "Release created, see:"
-            echo $body
-          fi
+      #     if [ $exit_code != 0 ]; then
+      #       echo "❌ Failed to create release in release registry, got:"
+      #       echo "--- raw body ---"
+      #       echo $body
+      #       echo "--- raw body ---"
+      #       exit $exit_code
+      #     else
+      #       echo "Release created, see:"
+      #       echo $body
+      #     fi
 
 test:
   steps:
@@ -249,54 +249,54 @@ promoteToPublic:
           echo "🚢 Please check the associated CI build to ensure the process completed".
   finalize:
     steps:
-      - name: 'Promote on release registry'
-        cmd: |
-          echo "Promoting terraform-aws-executors {{version}} release on release registry"
-          body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '' "https://releaseregistry.sourcegraph.com/v1/releases/terraform-aws-executors/{{version}}/promote")
-          exit_code=$?
-
-          if [ $exit_code != 0 ]; then
-            echo "❌ Failed to promote release on release registry, got:"
-            echo "--- raw body ---"
-            echo $body
-            echo "--- raw body ---"
-            exit $exit_code
-          else
-            echo "Release promoted, see:"
-            echo $body
-          fi
-      # - name: git:tag
+      # - name: 'Promote on release registry'
       #   cmd: |
-      #     set -eu
+      #     echo "Promoting terraform-aws-executors {{version}} release on release registry"
+      #     body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '' "https://releaseregistry.sourcegraph.com/v1/releases/terraform-aws-executors/{{version}}/promote")
+      #     exit_code=$?
 
-      #     # Branches
-      #     internal_branch="internal/release-{{version}}"
-      #     promote_branch="promote/release-{{version}}"
-      #     release_branch="release-{{version}}"
+      #     if [ $exit_code != 0 ]; then
+      #       echo "❌ Failed to promote release on release registry, got:"
+      #       echo "--- raw body ---"
+      #       echo $body
+      #       echo "--- raw body ---"
+      #       exit $exit_code
+      #     else
+      #       echo "Release promoted, see:"
+      #       echo $body
+      #     fi
+      - name: git:tag
+        cmd: |
+          set -eu
 
-      #     # Create the final branch holding the tagged commit
-      #     git checkout "${promote_branch}"
-      #     git switch -c "${release_branch}"
-      #     git tag {{version}}
-      #     git push origin ${release_branch} --tags
+          # Branches
+          internal_branch="internal/release-{{version}}"
+          promote_branch="promote/release-{{version}}"
+          release_branch="release-{{version}}"
 
-      #     # Web URL to the tag
-      #     tag_url="https://github.com/sourcegraph/terraform-aws-executors/tree/{{version}}"
+          # Create the final branch holding the tagged commit
+          git checkout "${promote_branch}"
+          git switch -c "${release_branch}"
+          git tag {{version}}
+          git push origin ${release_branch} --tags
 
-      #     # Annotate PRs
-      #     cat << EOF | gh pr comment "$internal_branch" --body-file -
-      #     - :green_circle: Release has been promoted, see tag: $tag_url.
-      #     - :no_entry: Do not under any circumstance delete the branch holding the tagged commit (i.e. \`$release_branch\`).
-      #     - :arrow_right: You can safely close the PR and delete its a associated branch.
-      #     EOF
+          # Web URL to the tag
+          tag_url="https://github.com/sourcegraph/terraform-aws-executors/tree/{{version}}"
 
-      #     cat << EOF | gh pr comment "$promote_branch" --body-file -
-      #     - :green_circle: Release has been promoted, see tag: $tag_url.
-      #     - :no_entry: Do not under any circumstance delete the branch holding the tagged commit (i.e. \`$release_branch\`).
-      #     - :arrow_right: You can safely close that PR and delete its a associated branch.
-      #     EOF
+          # Annotate PRs
+          cat << EOF | gh pr comment "$internal_branch" --body-file -
+          - :green_circle: Release has been promoted, see tag: $tag_url.
+          - :no_entry: Do not under any circumstance delete the branch holding the tagged commit (i.e. \`$release_branch\`).
+          - :arrow_right: You can safely close the PR and delete its a associated branch.
+          EOF
 
-      #     # Annotate build
-      #     cat << EOF | buildkite-agent annotate --style info
-      #     Promoted release is **publicly available** through a git tag at [\`{{version}}\`](https://github.com/sourcegraph/terraform-aws-executors/tree/{{version}}).
-      #     EOF
+          cat << EOF | gh pr comment "$promote_branch" --body-file -
+          - :green_circle: Release has been promoted, see tag: $tag_url.
+          - :no_entry: Do not under any circumstance delete the branch holding the tagged commit (i.e. \`$release_branch\`).
+          - :arrow_right: You can safely close that PR and delete its a associated branch.
+          EOF
+
+          # Annotate build
+          cat << EOF | buildkite-agent annotate --style info
+          Promoted release is **publicly available** through a git tag at [\`{{version}}\`](https://github.com/sourcegraph/terraform-aws-executors/tree/{{version}}).
+          EOF
